### ISSUE TITLE
PHP Notice:  Undefined index: auth_token in /public_html/wp-content/plugins/expertstatsplugin-master/classes/api_calls.php on line 87

### ISSUE THREAD

**Issue by mohammadmursaleen** [codeablehq/expertstatsplugin#60]
We have been using this plugin for Codeable in past. It seems like its not working any more. While debugging I figured out that "auth_token" is missing in the initial login request. Is there any change on the API end? Or am I missing something?

> Getting following error in the debug log;

`
PHP Notice:  Undefined index: auth_token in /public_html/wp-content/plugins/expertstatsplugin-master/classes/api_calls.php on line 87
`

**Comment by cfc1020** [comment]
Hi everyone,
Thank you for submitting this issue.
For a security reason and consistent response layouts, we've recently introduced a couple of changes in `sign-in` and `sign-up` endpoint responses.
According to them, we no longer provide `auth-token` property in the response body. The new place where it lives is **headers**. Like you set it when making subsequent requests in _the_ _request headers_, now it comes back in _the reponse headers_ of necessary endpoints(`sing-in`, `sign-up` and `token-renew`).
So that this plugin needs updating to reflect the above changes.
I am more than happy to provide you guys with more details if needs be. Any PR's are very welcome.

Thank you all.

**Comment by mohammadmursaleen** [comment]
@cfc1020 thanks for the details for the changes in the API response. 🔍
@spyrosvl thanks for the fix. 🛠
Its working perfect now! 👍
